Fix ValueError in list_lvm_physical_volumes
When you pvcreate a new physical volume but don't add it to a volume
group, disk-inventory fails with

    Traceback (most recent call last):
      File "./disk-inventory", line 444, in <module>
        main()
      File "./disk-inventory", line 366, in main
        usage_width = max(usage_width, len(info.get_partition_usage(partition)))
      File "./disk-inventory", line 315, in get_partition_usage
        pv = self._lvm_pvs.get(partition_name)
      File "./disk-inventory", line 69, in _lvm_pvs
        (pv.device, pv) for pv in self.list_lvm_physical_volumes())
      File "./disk-inventory", line 203, in list_lvm_physical_volumes
        used_extents, uuid) = line.strip().split(':')
    ValueError: need more than 1 value to unpack

because pvdisplay -c prints

      /dev/sda9:fridge:976755038:-1:8:8:-1:4096:119232:72373:46859:cGLoDM-0HFH-u8X8-66T7-2u6k-LM13-6fyNVk
      /dev/sdb9:fridge:976755038:-1:8:8:-1:4096:119232:72373:46859:zLNTe2-usSn-9cJC-Atqa-wjwX-dUsQ-3jtI3E
      "/dev/sdc2" is a new physical volume of "231.95 GiB"
      /dev/sdc2::486443376:-1:0:0:-1:0:0:0:0:VUA1rj-ZAdJ-VxuO-Cbb0-8DQz-B5Yf-zRuR2x